version: '3'
services:
  db:
    image: postgres:14.2-alpine
    restart: always
    volumes:
      - ./create-dev-db.sh:/docker-entrypoint-initdb.d/create-dev-db.sh
    ports:
      - '5432:5432'
    environment:
      POSTGRES_MULTIPLE_DATABASES: hopon_dev,hopon_test
      POSTGRES_USER: hopon
      POSTGRES_PASSWORD: hopon
  redis:
      container_name: cache
      image: redis
      ports:
        - 6379:6379
      volumes:
        - redis:/data

volumes:
  redis:
    driver: local