export enum RideNotificationTypeEnum {
  RIDE_REQUEST = 'RIDE_REQUEST',
  RIDE_ACCEPTED = 'RIDE_ACCEPTED',
  RIDE_REJECTED = 'RIDE_REJECTED',
  RIDE_COMPLETED = 'RIDE_COMPLETED',
  FARE_UPDATE = 'FARE_UPDATE',
}
